workspace 'SwiftTBot.xcworkspace'

target 'SwiftTBot_iOS' do
	use_frameworks!
	project 'SwiftTBot.xcodeproj'
	platform :ios, '9.0'
	pod 'ObjectMapper', '~> 2.2'
end

target 'SwiftTBot_OSX' do
	use_frameworks!
	project 'SwiftTBot.xcodeproj'
	platform :osx, '10.10'
	pod 'ObjectMapper', '~> 2.2'
end
