platform :osx, '10.9'
use_frameworks!

workspace 'EchoBotExample.xcworkspace'

target 'EchoBotExample' do
	xcodeproj 'EchoBotExample.xcodeproj'
	pod 'ObjectMapper', :git => 'https://github.com/mixalich7b/ObjectMapper.git'
	pod 'SwiftTBot', :path => '../../'
end
